TestMVC/Models/SiteLocaleModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TestMVC.Models
{
    public class SiteLocaleModel
    {
        public SiteLocaleModel(String Eng, String TH)
        {
            this.Engg = Eng;
            this.THH = TH;
        }
        public String Engg { get; set; }
        public String THH { get; set; }
    }
}

TestMVC/ViewModels/ErrorViewModel.cs
using System;

namespace TestMVC.ViewModels
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TestMVC/ViewModels/MenuViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TestMVC.ViewModels
{
    public class MenuViewModel
    {
        public String Username { get; set; }
    }
}

TestMVC/ViewModels/UserViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TestMVC.ViewModels
{
    public class UserViewModel
    {
        public String Name { get; set; }
        public int Result { get; set; }
        public List<SelectListItem> Options { get; set; } = new List<SelectListItem>();
    }
}

TestMVC/ViewModels/WorkShopTableModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TestMVC.ViewModels
{
    public class WorkShopTableModel
    {
        //[Required(ErrorMessage = "Input is null")]
        public string SearchName { get; set; }
        public List<A> RowList { get; set; }
    }
    public class A
    {
        public int Number { get; set; }
        public String Name { get; set; }
        public int Price { get; set; }
        public DateTime Date { get; set; }
    }
}

TestMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TestMVC.Configurations;
using TestMVC.Models;
using TestMVC.ViewModels;

namespace TestMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguratonContext configurationContext;
        //private readonly IConfiguration config;
        //public readonly List<A> RowDataList = new List<A>
        //{
        //     new A
        //        {
        //            Number = 1,
        //            Name = "Name1",
        //            Price = 20,
        //            Date = new DateTime(2000,1,10)
        //        },
        //        new A
        //        {
        //            Number = 2,
        //            Name = "Name2",
        //            Price = 20,
        //            Date = new DateTime(2000,1,10)
        //        },
        //        new A
        //        {
        //            Number = 2,
        //            Name = "Name2",
        //            Price = 20,
        //            Date = new DateTime(2000,1,10)
        //        },
        //};

        public HomeController(ILogger<HomeController> logger, 
            IConfiguration config, IConfiguratonContext configurationContext)
        {
            _logger = logger;
            this.configurationContext = configurationContext;
            //this.config = config;
        }

        public IActionResult Index()
        {
            //var model = new UserViewModel();
            //model.Name = "Thanapath";
            var model = new UserViewModel
            {
                Name = "Thanapath",
                Options = new List<SelectListItem>
                    {
                        new SelectListItem("Option 1","1"),
                        new SelectListItem("Option 2","2"),
                        new SelectListItem("Option 3","3")
                    }
            };
            return View(model);
        }

        public IActionResult Link(int id)
        {
            return View("Index");
        }

        [HttpPost]
        public IActionResult Index(UserViewModel model)
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [HttpPost]
        public IActionResult WorkTable(WorkShopTableModel serch)
        {

            var model = new List<A>
            {
                new A
                {
                    Number = 1,
                    Name = "Name1",
                    Price = 20,
                    Date = new DateTime(2000,1,10)
                },
                new A
                {
                    Number = 2,
                    Name = "Name2",
                    Price = 20,
                    Date = new DateTime(2000,1,10)
                },
                new A
                {
                    Number = 2,
                    Name = "Name2",
                    Price = 20,
                    Date = new DateTime(2000,1,10)
                },

            };

            WorkShopTableModel workShopTableModel = new WorkShopTableModel()
            {
                RowList = model,
            };

            return View("WorkShopTable", workShopTableModel);
        }


        public IActionResult WorkTable()
        {
            //var siteLocal = new SiteLocaleModel(config["SiteLocale:ENG"], config["SiteLocale:TH"]);
            //var demo = config["Demo:Cat"].ToString();
            //var demo1 = Convert.ToInt32(config["CachingDays"]);
            var siteLocal = configurationContext.GetSiteLocal();

            //WorkShopTableModel workShopTableModel = new WorkShopTableModel();
            //workShopTableModel.RowList = RowDataList;

            var model = new List<A>
            {
                new A
                {
                    Number = 1,
                    Name = "Name1",
                    Price = 20,
                    Date = new DateTime(2000,1,10)
                },
                new A
                {
                    Number = 2,
                    Name = "Name2",
                    Price = 20,
                    Date = new DateTime(2000,1,10)
                },
                new A
                {
                    Number = 2,
                    Name = "Name2",
                    Price = 20,
                    Date = new DateTime(2000,1,10)
                },

            };

            WorkShopTableModel workShopTableModel = new WorkShopTableModel()
            {
                RowList = model,
            };

            return View("WorkShopTable", workShopTableModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestMVC/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestMVC.ViewModels;

namespace TestMVC.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var model = new MenuViewModel
            {
                Username = "Thanapath Yam"
            };
            return View(model);
        }
    }
}

TestMVC/Views/Home/Index.cshtml
@model UserViewModel;
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <a href="@Url.Action("Link","Home",new { id = "13"})">link</a>
    <a asp-action="Link" asp-controller="Home" asp-route-id="13">link</a>

    <form asp-action="Index" asp-controller="Home" method="post">
        <input type="text" asp-for="Name" />

        <select asp-for="Result" asp-items="Model.Options">
            <option value="">-- Plese Select --</option>
        </select>

        <button type="submit">Submit</button>
    </form>

    @Model.Name
    <partial name="TestPartial">

        <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TestMVC/Views/Home/TestPartial.cshtml
@model UserViewModel;
@{
    var text = "hello";
}

<div class="text-center">
    <h1 class="display-4">Welcome, @*@text*@ @Model.Name</h1>
</div>

TestMVC/Views/Home/WorkShopTable.cshtml
@model WorkShopTableModel

<form asp-action="WorkTable" asp-controller="Home" method="post">
@*<div class="text-danger" asp-validation-summary="All"></div>*@
    <div class="form-row align-items-center">
        <div class="col-auto">
            <label class="sr-only" for="inlineFormInput">Name</label>
            <input type="text" asp-for="SearchName" form-control mb-2" id="inlineFormInput" placeholder="plese input">
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-primary mb-2">Submit</button>
        </div>
    </div>
        <span class="text-danger" asp-validation-for="SearchName"></span>
</form>



<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Product Name</th>
            <th scope="col">Price (Bath)</th>
            <th scope="col">Expired Date</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.RowList.Count; i++)
        {
            <tr>
                <td>
                    @Model.RowList[i].Number
                </td>
                <td>
                    @Model.RowList[i].Name
                </td>
                <td>
                    @Model.RowList[i].Price
                </td>
                <td>
                    @Model.RowList[i].Date
                </td>
            </tr>
        }
    </tbody>
</table>

TestMVC/Views/Shared/Components/Menu/Default.cshtml
@model MenuViewModel
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestMVC</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="WorkTable">WorkTable</a>
                </li>
            </ul>
        </div>
        <div class="float-right">
            <span>Hello, @Model.Username</span> | <a href="#">Logout</a>
        </div>
    </div>
</nav>

TestMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
    <vc:menu></vc:menu>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TestMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/jQuery-Bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>